---
- name: Copy files UI
  become: yes
  become_method: sudo
  copy:
    src: .env
    dest: /home/ubuntu/movies-ui/.env
    owner: ubuntu

- name: Copy files API
  become: yes
  become_method: sudo
  copy:
    src: .env
    dest: /home/ubuntu/movie-api/.env
    owner: ubuntu

- name: Run Server api
  become: yes
  become_method: sudo
  shell:
    cmd:  |
      cd /home/ubuntu/
      sudo su -c "node /home/ubuntu/movies-ui/server.js &" santiago